/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-22 08:40:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/java_web/foodtruck/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hungry_truck/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1610516075936L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    .mypage{\r\n");
      out.write("\t\tmargin-left:auto; margin-right:auto; margin-top:70px;\r\n");
      out.write("\t\twidth: 423px; max-min:423px; height:644px; max-height:644px;\r\n");
      out.write("\t\toverflow:auto; padding:10px;\r\n");
      out.write("\t}\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("        <main class=\"mypage\">\r\n");
      out.write("         <div>\r\n");
      out.write("              <h3>마이페이지</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"pt-4\">\r\n");
      out.write("\t         <h5 style=\"display:inline;\">정보수정</h5>\r\n");
      out.write("\t         <span style=\"text-decoration:underline; font-size:12px;\">회원정보를 수정할 수 있어요!</span>\r\n");
      out.write("\t         <input type=\"button\" class=\"btn btn-primary\" value=\"수정하기\" id=\"userEdit\" style=\"float:right; font-size:12px;  height:30px; width:70px;\"/>\r\n");
      out.write("          \t<hr>\r\n");
      out.write("          \t<div  style=\"display:inline;\">\r\n");
      out.write("          \t\t<img src=\"/resources/image/profile.jpg\" width=\"100px\" style=\"margin-right:80px; float:left; border-radius:100px; position:relative; left:20px;\">\r\n");
      out.write("\t          \t<ul style=\"font-size:14px; position:relative; top:10px;\">\r\n");
      out.write("\t          \t\t<li><b>admin</b> 님</li>\r\n");
      out.write("\t          \t\t<li>내가 찜한 밥차 <b>0</b> 개</li>\r\n");
      out.write("\t          \t\t<li>내가 쓴 리뷰 <b>0</b> 개</li>\r\n");
      out.write("\t          \t\t<li>내가 쓴 글 <b>0</b> 개</li>\r\n");
      out.write("\t          \t</ul>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"pt-4\">\r\n");
      out.write("\t         <h5 style=\"display:inline;\">내가 찜한 밥차</h5>\r\n");
      out.write("\t         <span style=\"text-decoration:underline; font-size:12px;\">찜해놓은 밥차를 한눈에 볼수있어요!</span>\r\n");
      out.write("\t         <input type=\"button\" class=\"btn btn-primary\" value=\"더보기\" onclick=\"#\" style=\"float:right; font-size:13px;  height:30px; width:70px;\"/>\r\n");
      out.write("          \t<hr>\r\n");
      out.write("          \t<div>\r\n");
      out.write("          \t\t<a href=\"#\"><img src=\"/resources/image/bobcha_icon.png\" width=\"85px\" style=\"margin-right:10px;\"></a>\r\n");
      out.write("          \t\t<a href=\"#\"><img src=\"/resources/image/bobcha_icon.png\" width=\"85px\" style=\"margin-right:10px;\"></a>\r\n");
      out.write("          \t\t<a href=\"#\"><img src=\"/resources/image/bobcha_icon.png\" width=\"85px\" style=\"margin-right:10px;\"></a>\r\n");
      out.write("          \t\t<a href=\"#\"><img src=\"/resources/image/bobcha_icon.png\" width=\"85px\"></a>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"pt-4\">\r\n");
      out.write("            <h5 style=\"display:inline;\">내가쓴 리뷰</h5>\r\n");
      out.write("            <span style=\"text-decoration:underline; font-size:12px;\">내가쓴 리뷰를 모아볼 수 있어요!</span>\r\n");
      out.write("            <input type=\"button\" class=\"btn btn-primary\" value=\"더보기\" onclick=\"#\" style=\"float:right; font-size:13px;  height:30px; width:70px;\"/>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <table class=\"table table-striped\" style=\"position:relative; bottom:20px;\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"width:55px; text-align:center;\">번호</th>\r\n");
      out.write("                  <th style=\"text-align:center;\">제목</th>\r\n");
      out.write("                  <th style=\"width:120px; text-align:center;\">날짜</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"text-align:center;\">3</th>\r\n");
      out.write("                  <td>여기 존맛탱입니다.</td>\r\n");
      out.write("                  <td style=\"text-align:center;\">2020-01-05</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"text-align:center;\">2</th>\r\n");
      out.write("                  <td>여기 별로예요!!</td>\r\n");
      out.write("                  <td style=\"text-align:center;\">2020-01-04</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"text-align:center;\">1</th>\r\n");
      out.write("                  <td>여기 너무 비쌉니다.</td>\r\n");
      out.write("                  <td style=\"text-align:center;\">2020-01-03</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"pt-4\" style=\"position:relative; bottom:30px;\">\r\n");
      out.write("            <h5 style=\"display:inline;\">내가쓴 글</h5>\r\n");
      out.write("            <span style=\"text-decoration:underline; font-size:12px;\">내가쓴 글을 모아볼 수 있어요!</span>\r\n");
      out.write("            <input type=\"button\" class=\"btn btn-primary\" value=\"더보기\" onclick=\"#\" style=\"float:right; font-size:13px;  height:30px; width:70px;\"/>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <table class=\"table table-striped\" style=\"position:relative; bottom:20px;\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"width:55px; text-align:center;\">번호</th>\r\n");
      out.write("                  <th style=\"text-align:center;\">제목</th>\r\n");
      out.write("                  <th style=\"width:120px; text-align:center;\">날짜</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"text-align:center;\">3</th>\r\n");
      out.write("                  <td>밥차 화이팅!! 취업잘해라!!</td>\r\n");
      out.write("                  <td style=\"text-align:center;\">2020-01-05</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"text-align:center;\">2</th>\r\n");
      out.write("                  <td>곱창차 몇시에 오나요?</td>\r\n");
      out.write("                  <td style=\"text-align:center;\">2020-01-04</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr style=\"height:20px;\">\r\n");
      out.write("                  <th style=\"text-align:center;\">1</th>\r\n");
      out.write("                  <td>안녕하세요. 가입인사드립니다.</td>\r\n");
      out.write("                  <td style=\"text-align:center;\">2020-01-03</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"pt-4\" style=\"position:relative; bottom:60px;\">\r\n");
      out.write("\t         <h5 style=\"display:inline;\">회원탈퇴</h5>\r\n");
      out.write("\t         <span style=\"text-decoration:underline; font-size:12px;\">정말 떠나실건가요?</span>\r\n");
      out.write("\t         <input type=\"button\" class=\"btn btn-primary\" value=\"탈퇴하기\" id=\"userDel\" style=\"float:right; font-size:13px; height:30px; width:70px;\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          </main>\r\n");
      out.write("          \r\n");
      out.write("    <script>\r\n");
      out.write("\t\t$(document).ready(function(){\t\t\r\n");
      out.write("\t\t\t<!-- 회원정보 수정화면 -->\r\n");
      out.write("\t\t\t$('#userEdit').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/userEdit');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 회원탈퇴화면 -->\r\n");
      out.write("\t\t\t$('#userDel').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/userDel');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
