/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-03-16 07:45:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/java_web/foodtruck/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hungry_truck/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1610516075936L));
    _jspx_dependants.put("/WEB-INF/views/review/map.jsp", Long.valueOf(1615880720282L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>홈</title>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"/resources/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- 메인 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/main.css\"></link>\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--다음 주소 활용 -->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"./resources/js/postcode.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- NaverMaps API \r\n");
      out.write("<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=853s8g0fk9&callback=CALLBACK_FUNCTION\"></script>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!-- KakaoMaps API -->\r\n");
      out.write("<!-- services와 clusterer, drawing 라이브러리 불러오기 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=c77113a5adfb4ed207e26c3c3e09d302&libraries=services,clusterer,drawing\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#a6b9c0; font-family:'Hanna', sans-serif;\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t<!-- 좌측 화면 -->\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<img id=\"logo\" src=\"/resources/image/logo.png\" width=\"100%\"/>\r\n");
      out.write("\t\t\t\t<br><hr>\r\n");
      out.write("\t\t\t\t<div style=\"padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.todayCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("명이 오늘 방문하셨어요.</p>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bobchaCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개의 밥차가 여러분을 기다리고 있어요!</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"border rounded overflow-hidden mb-4 shadow-sm position-relative\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col p-4 d-flex flex-column position-static\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"d-inline-block mb-2 text-primary\">What is BOBCHA?</strong>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("\t\t\t\t\t\t밥차는 좀처럼 만나기 힘든 푸드트럭의 <br>\r\n");
      out.write("\t\t\t\t\t\t위치와 리뷰를 나누는 커뮤니티 웹 어플리케이션 입니다. <br>\r\n");
      out.write("\t\t\t\t\t\t우측의 지도를 통해서 다양한 정보를 유저들과 공유하세요!\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"border rounded overflow-hidden mb-4 shadow-sm position-relative\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col p-4 d-flex flex-column position-static\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"d-inline-block mb-2 text-primary\" style=\"color:#E28FAD;\">Why did you make it?</strong>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t내 집근처에 먹을게 없어요. <br>\r\n");
      out.write("\t\t\t\t\t\t\t푸드트럭이 언제나타나는지 알수가 없어요. <br>\r\n");
      out.write("\t\t\t\t\t\t\t가격,운영시간,서비스,평점을 나누고 싶어요. \r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><hr><br>\r\n");
      out.write("\t\t\t\t<p align=\"center\">Copyright by <b>issac</b></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 우측 화면 -->\r\n");
      out.write("\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t<div class=\"right\" id=\"background\">\r\n");
      out.write("\t\t\t\t\t<div class=\"showMenu\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 네이버지도 API 넣기 \r\n");
      out.write("\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map\" style=\"width:100%;height:670px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- KakaoMap API 넣기 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map\" style=\"width:100%;height:650px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("#rvr_edit{\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight:230px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tbackground-color:#d6dee2;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:400px;\r\n");
      out.write("\tleft:1025px;\r\n");
      out.write("\tmargin-top:-50px;\r\n");
      out.write("\tmargin-left:-150px;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tz-index:1000; /* position 속성이 absolute 이거나 fixed 이면 요소가 겹쳐지는 순서를 제어할 수 있다. 갑싱 큰것이 먼저 나온다.*/\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"clickEvent\">\r\n");
      out.write("\t<!-- 리뷰 등록 화면 -->\r\n");
      out.write("\t<form method=\"post\" action=\"/review/review_ok\" enctype=\"multipart/form-data\" onclick=\"return checkReview()\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rv_lat\" name=\"rv_lat\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rv_lng\" name=\"rv_lng\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rv_writer\" name=\"rv_writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t<div id=\"reviewMod\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<!-- 상시 감추어 놓음 -->\r\n");
      out.write("\t\t\t<h4 style=\"margin-top: 10px;\">밥차등록</h4>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"reviewText\">가게명</label>\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" id=\"rv_title\" name=\"rv_title\" style=\"height: 30px;\" placeholder=\"가게이름을 써주세요.\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>가격정보</label>\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" id=\"rv_price\" name=\"rv_price\" style=\"height: 30px;\" placeholder=\"1인분에 3000원 / 개당 1000원 과 같이 남겨주세요.\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>출몰날짜</label>\r\n");
      out.write("\t\t\t\t<ul class=\"r_days\">\r\n");
      out.write("\t\t\t\t\t<li><label for=\"mon\">월</label> <input type=\"checkbox\" id=\"mon\" name=\"rv_days\" value=\"월\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"tue\">화</label> <input type=\"checkbox\" id=\"tue\" name=\"rv_days\" value=\"화\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"wed\">수</label> <input type=\"checkbox\" id=\"wed\" name=\"rv_days\" value=\"수\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"thu\">목</label> <input type=\"checkbox\" id=\"thu\" name=\"rv_days\" value=\"목\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"fri\">금</label> <input type=\"checkbox\" id=\"fri\" name=\"rv_days\" value=\"금\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"sat\">토</label> <input type=\"checkbox\" id=\"sat\" name=\"rv_days\" value=\"토\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"sun\">일</label> <input type=\"checkbox\" id=\"sun\" name=\"rv_days\" value=\"일\" /></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>출몰시간</label> \r\n");
      out.write("\t\t\t\t<select class=\"form-select\" id=\"rv_times\" name=\"rv_times\" style=\"width: 230px; height: 33px; float: right; position: relative;\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\" selected>밥차의 출몰시간을 알려주세요.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"00:00 ~ 06:00\">00:00 ~ 06:00</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"06:00 ~ 12:00\">06:00 ~ 12:00</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"12:00 ~ 18:00\">12:00 ~ 18:00</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"18:00 ~ 24:00\">18:00 ~ 24:00</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"reviewText\">제보자 리뷰</label>\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" rows=\"3\" cols=\"30\" id=\"rv_content\" name=\"rv_content\" style=\"resize: none;\"></textarea>\r\n");
      out.write("\t\t\t\t<!-- 내용이 출력되는 부분 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"review_rating form-group\">\r\n");
      out.write("\t\t\t\t<p style=\"float: left; margin-top: 10px;\">평점</p>\r\n");
      out.write("\t\t\t\t<div class=\"rating\" style=\"float: right; margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t<!-- 해당 별점을 클릭하면 해당 별과 그 왼쪽의 모든 별의 체크박스에 checked 적용 -->\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"rv_rating\" id=\"rating1\" value=\"1\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"rate_radio\" title=\"1점\"> <label for=\"rating1\"></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"rv_rating\" id=\"rating2\" value=\"2\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"rate_radio\" title=\"2점\"> <label for=\"rating2\"></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"rv_rating\" id=\"rating3\" value=\"3\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"rate_radio\" title=\"3점\"> <label for=\"rating3\"></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"rv_rating\" id=\"rating4\" value=\"4\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"rate_radio\" title=\"4점\"> <label for=\"rating4\"></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"rv_rating\" id=\"rating5\" value=\"5\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"rate_radio\" title=\"5점\"> <label for=\"rating5\"></label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t<label>가게사진</label>\r\n");
      out.write("\t\t\t\t<div class=\"filebox\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"rv_image_file\" class=\"form-control\" readonly\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"이미지 파일만 업로드 해주세요.\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 277px; height: 30px; display: inline;\" /> <label\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right; position: relative; text-align: center; width: 60px; height: 30px;\">첨부</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"rv_image_file\"\r\n");
      out.write("\t\t\t\t\t\t\taccept=\"image/jpeg, image/jpg, image/png\" multiple />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"float: right; margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"reviewSubBtn\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 60px; height: 30px; font-size: 13px;\">등록</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"reviewCloseBtn\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 60px; height: 30px; font-size: 13px;\"\r\n");
      out.write("\t\t\t\t\tonclick=\"reviewClose();\">취소</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<form method=\"post\" action=\"/review/review_del\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rv_no\" name=\"rv_no\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"dibs_no\" value=\"\"/>\r\n");
      out.write("\t\t<!-- 리뷰 보기 화면 -->\r\n");
      out.write("\t\t<div id=\"reviewCont\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<!-- 상시 감추어 놓음 -->\r\n");
      out.write("\t\t\t<a class=\"like\"><img src=\"\" id=\"like_img\" title=\"찜하기\" style=\"float:right; margin-top:15px; width:40px; height:auto;\"/></a>\r\n");
      out.write("\t\t\t<h4 style=\"margin-top:10px;\" id=\"shop_name\">가게명</h4>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<span id=\"rv_writer_read\"></span>님 께서 제보해주셨어요!\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<img src=\"\" id=\"shop_img\" style=\"width:100%; height:auto; border-radius:10px;\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>가격정보</label> \r\n");
      out.write("\t\t\t\t<p id=\"shop_price\"></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>출몰날짜</label>\r\n");
      out.write("\t\t\t\t<p id=\"shop_days\"></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>출몰시간</label>\r\n");
      out.write("\t\t\t\t<p id=\"shop_times\"></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"reviewText\">제보자 리뷰</label>\r\n");
      out.write("\t\t\t\t<p id=\"shop_review\"></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<p style=\"float: left; \">평점</p>\r\n");
      out.write("\t\t\t\t<span id=\"shop_ratings2\"></span>\r\n");
      out.write("\t\t\t\t<div class=\"rating\" id=\"shop_ratings\" style=\"float: right;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\"></div>\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"float: right; margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"review_del\" class=\"btn btn-primary\" style=\"width: 60px; height: 30px; font-size: 13px;\">삭제</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"review_edit\" class=\"btn btn-primary\" style=\"width: 60px; height: 30px; font-size: 13px;\">수정</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" style=\"width: 60px; height: 30px; font-size: 13px;\" onclick=\"reviewClose();\">취소</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear: both\"></div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("          \t\t<h5 id=\"rvr_count\"></h5>\r\n");
      out.write("          \t\t<input type=\"hidden\" id=\"rvr_replyer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("       \t\t\t<label>리뷰 남기기</label>\r\n");
      out.write("          \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<select class=\"form-select\" id=\"rvr_rating\" name=\"rvr_rating\" style=\"width:100px; height:33px; margin-bottom:2px; display:inline;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected>평점선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1점</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2점</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3점</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4점</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5점</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t          \t\t<input class=\"form-control\" id=\"rvr_replytext\" name=\"rvr_replytext\" style=\"width:165px; height:33px; display:inline;\"></input>\r\n");
      out.write("\t\t          \t<button type=\"button\" id=\"rvr_SubmitBtn\" class=\"btn btn-primary\" style=\"float:right; width:50px; height:33px; font-size:13px; \">등록</button>\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul id=\"rvr_replies\" style=\"list-style-type:none; padding:10px;\"></ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 리뷰 수정 화면 -->\r\n");
      out.write("\t<form method=\"post\" action=\"/review/review_edit\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<!-- 상시 감추어 놓음 -->\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rv_no2\" name=\"rv_no\" value=\"\"/>\r\n");
      out.write("\t\t<div id=\"reviewEdit\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<h4 style=\"margin-top: 10px;\">밥차수정</h4>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"reviewText\">가게명</label>\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" id=\"rv_title2\" name=\"rv_title\" style=\"height: 30px;\" placeholder=\"가게이름을 써주세요.\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>가격정보</label> \r\n");
      out.write("\t\t\t\t<input class=\"form-control\" id=\"rv_price2\" name=\"rv_price\" style=\"height: 30px;\" placeholder=\"1인분에 3000원 / 개당 1000원 과 같이 남겨주세요.\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>출몰날짜</label>\r\n");
      out.write("\t\t\t\t<ul class=\"r_days\">\r\n");
      out.write("\t\t\t\t\t<li><label for=\"mon\">월</label> <input type=\"checkbox\" id=\"mon2\" name=\"rv_days\" value=\"월\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"tue\">화</label> <input type=\"checkbox\" id=\"tue2\" name=\"rv_days\" value=\"화\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"wed\">수</label> <input type=\"checkbox\" id=\"wed2\" name=\"rv_days\" value=\"수\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"thu\">목</label> <input type=\"checkbox\" id=\"thu2\" name=\"rv_days\" value=\"목\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"fri\">금</label> <input type=\"checkbox\" id=\"fri2\" name=\"rv_days\" value=\"금\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"sat\">토</label> <input type=\"checkbox\" id=\"sat2\" name=\"rv_days\" value=\"토\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><label for=\"sun\">일</label> <input type=\"checkbox\" id=\"sun2\" name=\"rv_days\" value=\"일\" /></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label>출몰시간</label> \r\n");
      out.write("\t\t\t\t<select class=\"form-select\" id=\"rv_times2\" name=\"rv_times\" style=\"width: 230px; height: 33px; float: right; position: relative;\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\" selected>밥차의 출몰시간을 알려주세요.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"00:00 ~ 06:00\">00:00 ~ 06:00</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"06:00 ~ 12:00\">06:00 ~ 12:00</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"12:00 ~ 18:00\">12:00 ~ 18:00</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"18:00 ~ 24:00\">18:00 ~ 24:00</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t<label>가게사진</label>\r\n");
      out.write("\t\t\t\t<div class=\"filebox2\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"rv_image_file2\" class=\"form-control\" readonly placeholder=\"이미지 파일만 업로드 해주세요.\" style=\"width: 277px; height: 30px; display: inline;\" /> \r\n");
      out.write("\t\t\t\t\t\t<label for=\"file2\" style=\"float: right; position: relative; text-align: center; width: 60px; height: 30px;\">첨부</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" id=\"file2\" name=\"rv_image_file\" accept=\"image/jpeg, image/jpg, image/png\" multiple />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"float: right; margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"review_update\" class=\"btn btn-primary\" style=\"width: 60px; height: 30px; font-size: 13px;\">수정</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" style=\"width: 60px; height: 30px; font-size: 13px;\" onclick=\"reviewClose();\">취소</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div id=\"rvr_edit\" style=\"display:none;\">");
      out.write("\r\n");
      out.write("\t   \t<div class=\"modal-title\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t<p>리뷰댓글수정</p>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span id=\"rvr_edit_id\"></span>\r\n");
      out.write("\t\t\t<select class=\"form-select\" id=\"rvr_rating2\" style=\"width:100px; height:33px; margin-bottom:2px; float:right;\">\r\n");
      out.write("\t\t\t\t<option value=\"\" selected>평점선택</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">1점</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2점</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3점</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4점</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5점</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<textarea class=\"form-control\" rows=\"3\" cols=\"30\" id=\"rvr_replytext2\" style=\"resize:none;\"></textarea>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:right; padding:10px;\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"rvrEditBtn\" class=\"btn btn-primary\" style=\"width:60px; height:30px; font-size:13px;\" >수정</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"rvrDelBtn\" class=\"btn btn-primary\"  style=\"width:60px; height:30px; font-size:13px;\">삭제</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"rvrCloseBtn\" class=\"btn btn-primary\" style=\"width:60px; height:30px; font-size:13px;\">닫기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t//카카오맵 사용\r\n");
      out.write("\t\tvar container = document.getElementById('map');\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\tcenter : new kakao.maps.LatLng(33.450701, 126.570667),\r\n");
      out.write("\t\t\tlevel : 3\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar map = new kakao.maps.Map(container, options);\r\n");
      out.write("\r\n");
      out.write("\t\t// 주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("\t\tvar geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("\r\n");
      out.write("\t\t// 회원의 주소지를 가져옴.\r\n");
      out.write("\t\tvar myAddr = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.m_addr_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("\t\t// 주소로 좌표를 검색합니다\r\n");
      out.write("\t\tgeocoder.addressSearch(myAddr,function(result, status) {\r\n");
      out.write("\t\t\t// 정상적으로 검색이 완료됐으면 \r\n");
      out.write("\t\t\tif (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\t\t\t\t// 마커 이미지 경로\r\n");
      out.write("\t\t\t\tvar imageSrc = \"./resources/image/mylocation.png\";\r\n");
      out.write("\t\t\t    // 마커 이미지의 이미지 크기 입니다\r\n");
      out.write("\t\t\t    var imageSize = new kakao.maps.Size(40, 50); \r\n");
      out.write("\t\t\t    // 마커 이미지를 생성합니다    \r\n");
      out.write("\t\t\t    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar coords = new kakao.maps.LatLng(result[0].y,result[0].x);\r\n");
      out.write("\t\t\t\t// 결과값으로 받은 위치를 마커로 표시합니다\r\n");
      out.write("\t\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\tposition : coords,\r\n");
      out.write("\t\t\t\t\t\timage : markerImage\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\tvar iwContent = '<div style=\"width:150px;text-align:center;padding:10px 0;font-size:12px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.m_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님의 주변에 밥차를 등록해 보세요!</div>', \r\n");
      out.write("\t\t\t\tiwRemoveable = true;\r\n");
      out.write("\t\t\t\t// 인포윈도우로 장소에 대한 설명을 표시합니다\r\n");
      out.write("\t\t\t\tvar infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("\t\t\t\t\t\tcontent : iwContent,\r\n");
      out.write("\t\t\t\t\t\tremovable : iwRemoveable\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t//클릭시 인포윈도우가 표시되게함\r\n");
      out.write("\t\t\t\tkakao.maps.event.addListener(marker, 'click', function(){\r\n");
      out.write("\t\t\t\t\tinfowindow.open(map, marker);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t// 지도의 중심을 결과값으로 받은 위치로 이동시킵니다\r\n");
      out.write("\t\t\t\tmap.setCenter(coords);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//마커를 DB에서 꺼내와서 사용함\r\n");
      out.write("\t\t//마커 이미지의 이미지 주소입니다\r\n");
      out.write("\t\tvar imageSrc = \"./resources/image/marker_truck.png\";\r\n");
      out.write("\t\tvar rvlatlng = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rvlatlng}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //위경도+title\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 지도에 클릭 이벤트를 등록하여 리뷰를 등록함\r\n");
      out.write("\t\t// 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다\r\n");
      out.write("\t\tkakao.maps.event.addListener(map, 'click', function(mouseEvent) {\r\n");
      out.write("\t\t\t// 클릭한 위도, 경도 정보를 가져옵니다 \r\n");
      out.write("\t\t\tvar latlng = mouseEvent.latLng;\r\n");
      out.write("\t\t\t//form태그 내의 hidden값으로 위경도 값을 넘겨줌.\r\n");
      out.write("\t\t\t$('#rv_lat').val(latlng.getLat());\r\n");
      out.write("\t\t\t$('#rv_lng').val(latlng.getLng());\r\n");
      out.write("\t\t\tvar createMarker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t\tposition : latlng\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tif (confirm('이곳에 밥차를 등록하시겠습니까?') == true) {\r\n");
      out.write("\t\t\t\t$('#reviewMod').show();\r\n");
      out.write("\t\t\t\tif(checkReview()){\r\n");
      out.write("\t\t\t\t\tcreateMarker.setMap(map);\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treviewClose();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//모달 닫기\r\n");
      out.write("\t\tfunction reviewClose() {\r\n");
      out.write("\t\t\t$(\"#click\").off().on('click', function(){});\r\n");
      out.write("\t\t\t$('#reviewMod').hide();\r\n");
      out.write("\t\t\t$('#reviewCont').hide();\r\n");
      out.write("\t\t\t$('#reviewEdit').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//취소버튼을 눌렀을때 입력된 값을 모두 제거해줌\r\n");
      out.write("\t\t\t$('#like_img').attr('src','');\r\n");
      out.write("\t\t\t$('#rv_no').val('');\r\n");
      out.write("\t\t\t$('#dibs_no').val('');\r\n");
      out.write("\t\t\t$('#rv_title').val('');\r\n");
      out.write("\t\t\t$('#rv_price').val('');\r\n");
      out.write("\t\t\t$('#rv_content').val('');\r\n");
      out.write("\t\t\t$('#rv_times').val('');\r\n");
      out.write("\t\t\t$('#mon').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#tue').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#wed').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#thu').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#fri').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#sat').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#sun').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#rating1').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#rating2').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#rating3').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#rating4').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#rating5').prop(\"checked\",false);\r\n");
      out.write("\t\t\t$('#rv_image_file').val('');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"./resources/js/review.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- <script src=\"/resources/js/naver_map.js\"></script>-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 메뉴페이지 이동소스 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t//홈화면\r\n");
      out.write("\t\t\t$('#home').click(function(){\r\n");
      out.write("\t\t\t\tlocation.href('/');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//회원가입1\r\n");
      out.write("\t\t\t$('#join').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/member/userJoin');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//로그인\r\n");
      out.write("\t\t\t$('#login').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/member/userLogin');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//마이페이지\r\n");
      out.write("\t\t\t$('#mypage').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/mypage/mypage');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//게시판\r\n");
      out.write("\t\t\t$('#board').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/board/board');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//인포\r\n");
      out.write("\t\t\t$('#info').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/info/info');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//로그아웃\r\n");
      out.write("\t\t\t$('#logout').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/logout');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//페이지 get방식 확인후 넘겨줌\r\n");
      out.write("\t\t\tfunction Request(valuename){\r\n");
      out.write("\t\t\t\tvar rtnval = \"\";\r\n");
      out.write("\t\t\t\tvar nowAddress = unescape(location.href);\r\n");
      out.write("\t\t\t\tvar parameters = (nowAddress.slice(nowAddress.indexOf(\"?\")+1,nowAddress.length)).split(\"&\");\r\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < parameters.length ; i++){\r\n");
      out.write("\t\t\t\t\tvar varName = parameters[i].split(\"=\")[0];\r\n");
      out.write("\t\t\t\t\tif(varName.toUpperCase() == valuename.toUpperCase()){\r\n");
      out.write("\t\t\t\t\t\trtnval = parameters[i].split(\"=\")[1];\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn rtnval;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar value = Request(\"pv\");\r\n");
      out.write("\t\t\tif(value == 'board'){\r\n");
      out.write("\t\t\t\thistory.replaceState({}, null, location.pathname);\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/board/board');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(value == 'mypage'){\r\n");
      out.write("\t\t\t\thistory.replaceState({}, null, location.pathname);\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/mypage/mypage');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//세션값 확인\r\n");
      out.write("\t\t\tvar session = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(session == \"\"){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/member/userLogin');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main/main.jsp(32,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div style=\"margin-top:60px;\"></div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"profile\" align=\"center\">\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t<b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 님</b>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/main/main.jsp(37,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty m.m_profile}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"/resources/image/profile.jpg\" style=\"border-radius:100px; max-width:30px; max-height:30px; margin-right:10px;\">\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/main/main.jsp(40,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty m.m_profile}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"/resources/upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.m_profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"border-radius:100px; max-width:30px; max-height:30px; margin-right:10px;\">\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/main/main.jsp(49,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"menu\" style=\"height:200px;\">\r\n");
          out.write("\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"home\"><img src=\"/resources/image/home.png\" alt=\"홈\" title=\"홈\"/></a><br><br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"join\"><img src=\"/resources/image/join.png\" alt=\"회원가입\" title=\"회원가입\"/></a><br><br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"info\"><img src=\"/resources/image/info.png\" alt=\"문의\" title=\"문의\"/></a>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"menu\">\r\n");
          out.write("\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"home\"><img src=\"/resources/image/home.png\" alt=\"홈\" title=\"홈\"/></a><br><br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"mypage\"><img src=\"/resources/image/mypage.png\" alt=\"마이페이지\" title=\"마이페이지\"/></a><br><br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"board\"><img src=\"/resources/image/community.png\" alt=\"자유게시판\" title=\"자유게시판\"/></a><br><br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"info\"><img src=\"/resources/image/info.png\" alt=\"문의\" title=\"문의\"/></a><br><br>\r\n");
          out.write("\t\t\t\t\t<a href=\"\" id=\"logout\"><img src=\"/resources/image/logout.png\" alt=\"로그아웃\" title=\"로그아웃\"/></a>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/review/map.jsp(304,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/review/map.jsp(304,2) '${rvlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${rvlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/review/map.jsp(304,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("r");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t    // 마커 이미지의 이미지 크기 입니다\r\n");
            out.write("\t\t    var imageSize = new kakao.maps.Size(40, 50); \r\n");
            out.write("\t\t    // 마커 이미지를 생성합니다    \r\n");
            out.write("\t\t    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); \r\n");
            out.write("\t\t    // DB에 있는 위경도값 꺼내서 새로만들어줌\r\n");
            out.write("\t\t    var latlng = new kakao.maps.LatLng('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_lat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_lng}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t    // 마커를 생성합니다\r\n");
            out.write("\t\t    var markerlist = new kakao.maps.Marker({\r\n");
            out.write("\t\t        map: map, // 마커를 표시할 지도\r\n");
            out.write("\t\t        position: latlng, // 마커를 표시할 위치\r\n");
            out.write("\t\t        title : '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다\r\n");
            out.write("\t\t        image : markerImage // 마커 이미지 \r\n");
            out.write("\t\t    });\r\n");
            out.write("\t\t    // 마커에 클릭이벤트를 등록함\r\n");
            out.write("\t\t    kakao.maps.event.addListener(markerlist, 'click', function(){\r\n");
            out.write("\t\t    \t//내용보기\r\n");
            out.write("\t\t    \talert('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t    \t$('#reviewCont').show();\r\n");
            out.write("\t\t    \t$('#rv_no').val('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t    \t$('#rv_writer_read').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t    \tif('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'!='");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'){\r\n");
            out.write("\t\t    \t\t$('#review_del').hide();\r\n");
            out.write("\t\t    \t}\r\n");
            out.write("\t\t\t\t$('#shop_name').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');//가게이름\r\n");
            out.write("\t\t\t\tif('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_image_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'==''){\r\n");
            out.write("\t\t\t\t\t$('#shop_img').attr('src','/resources/image/bobcha_icon.png');\r\n");
            out.write("\t\t\t\t}else{\r\n");
            out.write("\t\t\t\t\t$('#shop_img').attr('src','/resources/upload");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_image_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');//가게사진\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t\t$('#shop_review').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');//내용\r\n");
            out.write("\t\t\t\t$('#shop_price').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');//가격\r\n");
            out.write("\t\t\t\t$('#shop_days').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_days}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');//출몰일\r\n");
            out.write("\t\t\t\t$('#shop_times').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_times}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');//시간\r\n");
            out.write("\t\t\t\t$('#shop_ratings').html('');\r\n");
            out.write("\t\t\t\tfor(var i=0; i<");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("; i++){\r\n");
            out.write("\t\t\t\t\t$('#shop_ratings').append('<img src=\"/resources/image/ratings.png\" width=\"40px;\"/>');//평점\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t    \t//찜버튼을 누를시\r\n");
            out.write("\t    \t\tvar rv_no = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\r\n");
            out.write("\t    \t\tvar rv_title = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\r\n");
            out.write("\t    \t\tvar m_id = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\r\n");
            out.write("\t    \t\tvar dibs_no = $('#dibs_no').val();\r\n");
            out.write("\t    \t\t\r\n");
            out.write("\t\t    \t$('.like').click(function(){\r\n");
            out.write("          \t\t\t$.ajax({\r\n");
            out.write("          \t\t\t\ttype:'put',\r\n");
            out.write("          \t\t\t\turl:'/dibs',\r\n");
            out.write("          \t\t\t\theaders:{\r\n");
            out.write("          \t\t\t\t\t\"Content-Type\":\"application/json\",\r\n");
            out.write("          \t\t\t\t\t\"X-HTTP-Method-Override\":\"PUT\"\r\n");
            out.write("          \t\t\t\t},\r\n");
            out.write("          \t\t\t\tdata:JSON.stringify({\r\n");
            out.write("          \t\t\t\t\trv_no:rv_no,\r\n");
            out.write("          \t\t\t\t\trv_title:rv_title,\r\n");
            out.write("          \t\t\t\t\tm_id:m_id,\r\n");
            out.write("          \t\t\t\t\tdibs_no:dibs_no\r\n");
            out.write("          \t\t\t\t}),\r\n");
            out.write("          \t\t\t\tdataType:'text',\r\n");
            out.write("          \t\t\t\tsuccess:function(data){\r\n");
            out.write("          \t\t\t\t\tif(data == 'SUCCESS'){\r\n");
            out.write("          \t\t\t\t\t    checkLike();\r\n");
            out.write("          \t\t\t\t\t}\r\n");
            out.write("          \t\t\t\t}\r\n");
            out.write("          \t\t\t});\r\n");
            out.write("\t\t    \t});\r\n");
            out.write("\t\t    \t\r\n");
            out.write("\t\t    \t\r\n");
            out.write("\t\t    \t//찜 여부확인\r\n");
            out.write("\t\t    \tfunction checkLike(){\r\n");
            out.write("\t\t    \t\t$.getJSON(\"/dibs/dibsCheck/\"+rv_no,function(data){\r\n");
            out.write("\t\t    \t\t\tif(data.dibs_check == '1'){\t\r\n");
            out.write("\t\t\t\t\t\t   \t$('#like_img').attr('src','/resources/image/like_on.png');\r\n");
            out.write("\t\t\t\t\t\t   \talert(data.dibs_no);\r\n");
            out.write("\t\t\t\t\t\t   \t$('#dibs_no').val(data.dibs_no);\r\n");
            out.write("\t\t    \t\t\t}\r\n");
            out.write("\t\t    \t\t});\r\n");
            out.write("\t\t\t\t   \t$('#like_img').attr('src','/resources/image/like_off.png');\r\n");
            out.write("\t\t    \t}\r\n");
            out.write("\t\t    \t\r\n");
            out.write("\t\t    \t//찜여부 확인\r\n");
            out.write("\t\t\t    checkLike();\r\n");
            out.write("\t\t    \t\r\n");
            out.write("\t\t\t\t//리뷰 댓글 불러오기\r\n");
            out.write("          \t\tgetAllList();\r\n");
            out.write("          \t\t\r\n");
            out.write("          \t\t//댓글목록\r\n");
            out.write("          \t\tfunction getAllList(){\r\n");
            out.write("          \t\t\t$.getJSON(\"/reviewReplies/all/\"+rv_no,function(data){\r\n");
            out.write("          \t\t\t\t//비동기식으로 받아온 데이터는 data매개변수에 저장\r\n");
            out.write("          \t\t\t\tvar str = \"\";\r\n");
            out.write("          \t\t\t\tvar num = 0;\r\n");
            out.write("          \t\t\t\t$(data).each(function(){//each()함수로 반복\r\n");
            out.write("          \t\t\t\t\tnum += 1;\r\n");
            out.write("          \t\t\t\t\tif(m_id == this.rvr_replyer){\r\n");
            out.write("\t          \t\t\t\t\tstr += \"<li data-rvr_no='\"+this.rvr_no+\"' class='rvrLi'>\" //data-r_no는 Ajax 속성값\r\n");
            out.write("\t          \t\t\t\t\t+ \"<span id='nick2'>\" +this.rvr_replyer+\"</span>\" + '[<img src=\"/resources/image/ratings.png\" width=\"20px;\"/>x'+ this.rvr_rating +']'+ \" : <span class='com' style='max-width:423px;'>\"\r\n");
            out.write("\t          \t\t\t\t\t+ this.rvr_replytext + \"</span>\"\r\n");
            out.write("\t          \t\t\t\t\t+ '<a style=\"float:right;\"><img src=\"/resources/image/mypage.png\" width=\"12px\" alt=\"댓글수정\" title=\"댓글수정\"/></a>'\r\n");
            out.write("\t          \t\t\t\t\t+ \"</li><br>\";\r\n");
            out.write("          \t\t\t\t\t}else{\r\n");
            out.write("\t          \t\t\t\t\tstr += \"<li data-rvr_no='\"+this.rvr_no+\"' class='rvrLi'>\" //data-r_no는 Ajax 속성값\r\n");
            out.write("\t          \t\t\t\t\t+ \"<span id='nick2'>\" +this.rvr_replyer + \"</span>\"+ '[<img src=\"/resources/image/ratings.png\" width=\"20px;\"/>x'+ this.rvr_rating +']'+ \" : <span class='com' style='max-width:423px;'>\"\r\n");
            out.write("\t          \t\t\t\t\t+ this.rvr_replytext + \"</span>\" + \"</li><br>\";\r\n");
            out.write("          \t\t\t\t\t}\r\n");
            out.write("          \t\t\t\t});\r\n");
            out.write("          \t\t\t\t$('#rvr_replies').html(str);\r\n");
            out.write("        \t\t    \t$('#rvr_count').text(num+'개의 리뷰가 있어요!');\r\n");
            out.write("          \t\t\t});\r\n");
            out.write("          \t\t}\r\n");
            out.write("          \t\t\r\n");
            out.write("          \t\t//댓글수정\r\n");
            out.write("          \t\t$('#rvr_replies').on('click','.rvrLi a',function(){\r\n");
            out.write("          \t\t\tvar rvr_replies = $(this).parent();//부모요소 -> li태그, this는 버튼\r\n");
            out.write("          \t\t\tvar rvr_no = rvr_replies.attr('data-rvr_no');//data-rv_no속성값 댓글번호 저장\r\n");
            out.write("          \t\t\tvar rvr_replyer = rvr_replies.children('#nick2').text();\r\n");
            out.write("          \t\t\tvar rvr_replytext = rvr_replies.children('.com').text();\r\n");
            out.write("          \t\t\t$('.modal-title').html(rvr_no); //댓글번호\r\n");
            out.write("          \t\t\t$('#rvr_edit_id').text(rvr_replyer);//작성자\r\n");
            out.write("          \t\t\t$('#rvr_replytext2').val(rvr_replytext);//댓글내용\r\n");
            out.write("          \t\t\t$('#rvr_edit').show();\r\n");
            out.write("          \t\t});\r\n");
            out.write("          \t\t\r\n");
            out.write("          \t\t//댓글수정창 닫기\r\n");
            out.write("          \t\t$('#rvrCloseBtn').click(function(){\r\n");
            out.write("          \t\t\t$('#rvr_edit').hide();\r\n");
            out.write("          \t\t});\r\n");
            out.write("          \t\t\r\n");
            out.write("          \t\t//댓글 수정 완료\r\n");
            out.write("          \t\t$('#rvrEditBtn').on('click',function(){\r\n");
            out.write("          \t\t\tvar rvr_no = $('.modal-title').html();\r\n");
            out.write("          \t\t\tvar rvr_replytext = $('#rvr_replytext2').val();//내용\r\n");
            out.write("          \t\t\tvar rvr_rating = $('#rvr_rating2').val();//평점\r\n");
            out.write("          \t\t\tif((rvr_rating=='')||rvr_replytext==''){\r\n");
            out.write("          \t\t\t\talert('평점과 내용을 입력해주세요.');\r\n");
            out.write("          \t\t\t\treturn false;\r\n");
            out.write("          \t\t\t}\r\n");
            out.write("          \t\t\t$.ajax({\r\n");
            out.write("          \t\t\t\ttype:'put', \r\n");
            out.write("          \t\t\t\turl:'/reviewReplies/'+rvr_no,\r\n");
            out.write("          \t\t\t\theaders:{\r\n");
            out.write("          \t\t\t\t\t\"Content-Type\":\"application/json\",\r\n");
            out.write("          \t\t\t\t\t\"X-HTTP-Method-Override\":\"PUT\"          \t\t\t\t\t\r\n");
            out.write("          \t\t\t\t},\r\n");
            out.write("          \t\t\t\tdata:JSON.stringify({\r\n");
            out.write("          \t\t\t\t\trvr_replytext:rvr_replytext,\r\n");
            out.write("          \t\t\t\t\trvr_rating:rvr_rating\r\n");
            out.write("          \t\t\t\t}),\r\n");
            out.write("          \t\t\t\tdataType:'text',\r\n");
            out.write("          \t\t\t\tsuccess:function(data){\r\n");
            out.write("          \t\t\t\t\tif(data == 'SUCCESS'){\r\n");
            out.write("          \t\t\t\t\t\talert('댓글이 수정되었어요.');\r\n");
            out.write("          \t\t\t\t\t\t$('#rvr_edit').hide();\r\n");
            out.write("          \t\t\t\t\t\tgetAllList();\r\n");
            out.write("          \t\t\t\t\t}\r\n");
            out.write("          \t\t\t\t}\r\n");
            out.write("          \t\t\t});\r\n");
            out.write("          \t\t});\r\n");
            out.write("          \t\t\r\n");
            out.write("          \t\t//댓글삭제\r\n");
            out.write("          \t\t$('#rvrDelBtn').on('click',function(){\r\n");
            out.write("          \t\t\tvar rvr_no = $('.modal-title').html();\r\n");
            out.write("          \t\t\t$.ajax({\r\n");
            out.write("          \t\t\t\ttype:'delete',\r\n");
            out.write("          \t\t\t\turl:'/reviewReplies/'+rvr_no,\r\n");
            out.write("          \t\t\t\theaders:{\r\n");
            out.write("          \t\t\t\t\t\"Content-Type\":\"application/json\",\r\n");
            out.write("          \t\t\t\t\t\"X-HTTP-Method-Override\":\"DELETE\"\r\n");
            out.write("          \t\t\t\t},\r\n");
            out.write("          \t\t\t\tdataType:'text',\r\n");
            out.write("          \t\t\t\tsuccess:function(data){\r\n");
            out.write("          \t\t\t\t\tif(data == 'SUCCESS'){\r\n");
            out.write("          \t\t\t\t\t\talert('댓글이 삭제되었어요.');\r\n");
            out.write("          \t\t\t\t\t\t$('#rvr_edit').hide();\r\n");
            out.write("          \t\t\t\t\t\tgetAllList();\r\n");
            out.write("          \t\t\t\t\t}\r\n");
            out.write("          \t\t\t\t}\r\n");
            out.write("          \t\t\t});\r\n");
            out.write("          \t\t});\r\n");
            out.write("          \t\t\r\n");
            out.write("          \t\t//댓글 추가\r\n");
            out.write("          \t\t$('#rvr_SubmitBtn').on('click',function(){\r\n");
            out.write("          \t\t\tvar rvr_replyer = $('#rvr_replyer').val();//작성자\r\n");
            out.write("          \t\t\tvar rvr_replytext = $('#rvr_replytext').val();//내용\r\n");
            out.write("          \t\t\tvar rvr_rating = $('#rvr_rating').val();//평점\r\n");
            out.write("          \t\t\tif((rvr_rating=='')||rvr_replytext==''){\r\n");
            out.write("          \t\t\t\talert('평점과 내용을 입력해주세요.');\r\n");
            out.write("          \t\t\t\treturn false;\r\n");
            out.write("          \t\t\t}else{\r\n");
            out.write("\t\t          \t\t$.ajax({\r\n");
            out.write("\t\t          \t\t\ttype:'post',\r\n");
            out.write("\t\t          \t\t\turl:'/reviewReplies',\r\n");
            out.write("\t\t          \t\t\theaders:{//http 헤더앞에 붙는 형식\r\n");
            out.write("\t\t          \t\t\t\t\"Content-Type\":\"application/json\",\r\n");
            out.write("\t\t          \t\t\t\t\"X-HTTP-Method-Override\":\"POST\"\r\n");
            out.write("\t\t          \t\t\t},\r\n");
            out.write("\t\t          \t\t\tdataType:'text',\r\n");
            out.write("\t\t          \t\t\tdata:JSON.stringify({//보내지는 자료가 JSON형태인 키,밸류\r\n");
            out.write("\t\t          \t\t\t\trv_no:rv_no,\r\n");
            out.write("\t\t          \t\t\t\trvr_rating:rvr_rating,\r\n");
            out.write("\t\t          \t\t\t\trvr_replyer:rvr_replyer,\r\n");
            out.write("\t\t          \t\t\t\trvr_replytext:rvr_replytext\r\n");
            out.write("\t\t          \t\t\t}),\r\n");
            out.write("\t\t          \t\t\tsuccess:function(data){\r\n");
            out.write("\t\t          \t\t\t\t//비동기식 성공시 호출되며 받아온데이터는 data매개변수에 저장\r\n");
            out.write("\t\t          \t\t\t\tif(data == 'SUCCESS'){\r\n");
            out.write("\t\t          \t\t\t\t\t$('#rvr_replytext').val('');\r\n");
            out.write("\t\t          \t\t\t\t\t$('#rvr_rating').val('');\r\n");
            out.write("\t\t          \t\t\t\t\talert('댓글이 등록되었어요.');\r\n");
            out.write("\t\t          \t\t\t\t\tgetAllList();\r\n");
            out.write("\t\t          \t\t\t\t}\r\n");
            out.write("\t\t          \t\t\t}\r\n");
            out.write("\t\t          \t\t});\r\n");
            out.write("\t          \t\t}\r\n");
            out.write("\t          \t});\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t//내용삭제\r\n");
            out.write("\t\t\t\t$('#review_del').click(function(){\r\n");
            out.write("\t\t\t\t\treviewClose();\r\n");
            out.write("\t\t\t\t\talert('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("님께서 등록하신 밥차가 삭제되었어요.');\r\n");
            out.write("\t\t\t\t});\r\n");
            out.write("\t\t\t\t//내용수정\r\n");
            out.write("\t\t\t\t$('#review_edit').click(function(){\r\n");
            out.write("\t\t\t\t\t$('#reviewCont').hide();\r\n");
            out.write("\t\t\t\t\t$('#reviewEdit').show();\r\n");
            out.write("\t\t\t    \t$('#rv_no2').val('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t\t\t\t$('#rv_title2').val('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t\t\t\t$('#rv_content2').text('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t\t\t\t$('#rv_price2').val('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.rv_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t\t\t\tif(checkReview()){\r\n");
            out.write("\t\t\t\t\t\treviewClose();\r\n");
            out.write("\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t});\r\n");
            out.write("\t\t    });\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
