/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-23 04:28:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>홈</title>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"/resources/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- 메인 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/main.css\"></link>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--다음 주소 활용 -->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"./resources/js/postcode.js\"></script>\r\n");
      out.write("<!-- NaverMaps API -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=853s8g0fk9\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=853s8g0fk9&callback=CALLBACK_FUNCTION\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#a6b9c0; font-family:'Hanna', sans-serif;\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"profile\" align=\"center\">\r\n");
      out.write("\t\t\t<img src=\"/resources/image/profile.jpg\" style=\"border-radius:100px; width:30px; margin-right:10px;\">\r\n");
      out.write("\t\t\t<b>admin 님</b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"home\"><img src=\"/resources/image/home.png\" alt=\"홈\" title=\"홈\"/></a><br><br>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"join\"><img src=\"/resources/image/join.png\" alt=\"회원가입\" title=\"회원가입\"/></a><br><br>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"login\"><img src=\"/resources/image/login.png\" alt=\"로그인\" title=\"로그인\"/></a><br><br>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"mypage\"><img src=\"/resources/image/mypage.png\" alt=\"마이페이지\" title=\"마이페이지\"/></a><br><br>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"board\"><img src=\"/resources/image/community.png\" alt=\"자유게시판\" title=\"자유게시판\"/></a><br><br>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"info\"><img src=\"/resources/image/info.png\" alt=\"문의\" title=\"문의\"/></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t<!-- 좌측 화면 -->\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<img id=\"logo\" src=\"/resources/image/logo.png\" width=\"100%\"/>\r\n");
      out.write("\t\t\t\t<br><hr>\r\n");
      out.write("\t\t\t\t<div class=\"border rounded overflow-hidden mb-4 shadow-sm position-relative\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col p-4 d-flex flex-column position-static\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"d-inline-block mb-2 text-primary\">What is BOBCHA?</strong>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("\t\t\t\t\t\t밥차는 좀처럼 만나기 힘든 푸드트럭의 <br>\r\n");
      out.write("\t\t\t\t\t\t위치와 리뷰를 나누는 커뮤니티 웹 어플리케이션 입니다. <br>\r\n");
      out.write("\t\t\t\t\t\t우측의 지도를 통해서 다양한 정보를 유저들과 공유하세요!\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"border rounded overflow-hidden mb-4 shadow-sm position-relative\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col p-4 d-flex flex-column position-static\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"d-inline-block mb-2 text-primary\">Why did you make it?</strong>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t내 집근처에 먹을게 없어요. <br>\r\n");
      out.write("\t\t\t\t\t\t\t푸드트럭이 언제나타나는지 알수가 없어요. <br>\r\n");
      out.write("\t\t\t\t\t\t\t가격,운영시간,서비스,평점을 나누고 싶어요. \r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><hr><br>\r\n");
      out.write("\t\t\t\t<p align=\"center\">Copyright by <b>issac</b></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 우측 화면 -->\r\n");
      out.write("\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t<div class=\"right\" id=\"background\">\r\n");
      out.write("\t\t\t\t\t<div class=\"showMenu\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 네이버지도 API 넣기 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map\" style=\"width:100%;height:670px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:100%;height:670px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"http://maps.googleapis.com/maps/api/js\"></script>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 메뉴페이지 이동소스 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//홈화면\r\n");
      out.write("\t\t\t$('#home').click(function(){\r\n");
      out.write("\t\t\t\tlocation.href('/');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//회원가입1\r\n");
      out.write("\t\t\t$('#join').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/member/userJoin');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//로그인\r\n");
      out.write("\t\t\t$('#login').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/userLogin');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//마이페이지\r\n");
      out.write("\t\t\t$('#mypage').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/mypage');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//게시판\r\n");
      out.write("\t\t\t$('#board').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/board');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//인포\r\n");
      out.write("\t\t\t$('#info').click(function(){\r\n");
      out.write("\t\t\t\t$('.showMenu').empty();\r\n");
      out.write("\t\t\t\t$('.showMenu').load('/info');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 네이버 맵 API 사용 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar mapOptions = {\r\n");
      out.write("\t\t    center: new naver.maps.LatLng(37.3595704, 127.105399),\r\n");
      out.write("\t\t    zoom: 10,\r\n");
      out.write("\t        zoomControl: true,\r\n");
      out.write("\t        zoomControlOptions: {\r\n");
      out.write("\t            style: naver.maps.ZoomControlStyle.SMALL,\r\n");
      out.write("\t            position: naver.maps.Position.TOP_RIGHT\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar map = new naver.maps.Map('map', mapOptions);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tnaver.maps.Event.once(map, 'init_stylemap', function() {\r\n");
      out.write("\t\t    //customControl 객체 이용하기\r\n");
      out.write("\t\t    var customControl = new naver.maps.CustomControl(locationBtnHtml, {\r\n");
      out.write("\t\t        position: naver.maps.Position.TOP_LEFT\r\n");
      out.write("\t\t    });\r\n");
      out.write("\r\n");
      out.write("\t\t    customControl.setMap(map);\r\n");
      out.write("\r\n");
      out.write("\t\t    naver.maps.Event.addDOMListener(customControl.getElement(), 'click', function() {\r\n");
      out.write("\t\t        map.setCenter(new naver.maps.LatLng(37.3595953, 127.1053971));\r\n");
      out.write("\t\t    });\r\n");
      out.write("\r\n");
      out.write("\t\t    //Map 객체의 controls 활용하기\r\n");
      out.write("\t\t    var $locationBtn = $(locationBtnHtml),\r\n");
      out.write("\t\t        locationBtnEl = $locationBtn[0];\r\n");
      out.write("\r\n");
      out.write("\t\t    map.controls[naver.maps.Position.LEFT_CENTER].push(locationBtnEl);\r\n");
      out.write("\r\n");
      out.write("\t\t    naver.maps.Event.addDOMListener(locationBtnEl, 'click', function() {\r\n");
      out.write("\t\t        map.setCenter(new naver.maps.LatLng(37.3595953, 127.1553971));\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
